local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}

  static_layer:
    enabled: true
    map_topic: /map

  inflation_layer:
    enabled: true
    cost_scaling_factor: 5
    inflation_radius: 0.3
  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {
      sensor_frame: base_link,
      data_type: LaserScan, 
      topic: /scan, 
      expected_update_rate: 0.5, 
      marking: true, 
      clearing: true,
      # min_obstacle_height: 0.0,
      # max_obstacle_height: 0.6
    }